### PR TITLE
Add chunked video upload functionality

### PR DESCRIPTION
**Pull request by akarambir**
This is a simple implementation of twitter's [chunked media upload api](https://dev.twitter.com/rest/public/uploading-media#chunkedupload). Following points need to be noted:

- I have added a separate endpoint for this instead of using the `upload_media`.
- It needs a media_type as required by twitter. Though in my own project, I am using python mimetypes module.
- It uses `.seek` to calculate size of media file if not given.
- As twitter have a limit of 5mb per chunk upload, I am uploading in 1mb chunks. I had to use `StringIO` as `helpers._transparent_params` is checking for `read` attribute on file contents.

Please let me know what you guys think.

### CODE REVIEW

**Comment by akarambir** [comment]
I also had to change something in `api.py` as twitter returns 204 No Content for append calls

**Comment by michaelhelmick** [comment]
This look good, thanks!

**Comment by djedi** [comment]
When will this update be on PyPI?

**Comment by michaelhelmick** [comment]
@djedi Sorry, been a bit busy. I'll do a release this week!

**Comment by akarambir** [comment]
:+1:

**Pull request merged**
