### PR TITLE
Fix URLs for multiple media in html_for_tweet()

### PR DESCRIPTION
**Pull request by philgyford**
* I moved the `html_for_tweet()` tests into their own file.

* Then fixed an issue with `html_for_tweet()` displaying media links when there are multiple media items.

    As an example, one tweet that had multiple images was having its URL(s) come out something like:

    > `wNc6uJklg" rel="external">pic.twitter.com/OwNc6uJklg</a>wNc6uJklg" rel="external">pic.twitter.com/OwNc6uJklg</a>`
    
    rather than
    > `<a href="https://t.co/OwNc6uJklg" class="twython-media">pic.twitter.com/OwNc6uJklg</a>`

### CODE REVIEW

**Comment by philgyford** [comment]
Hmm, damn, not sure what I've done to reduce coverage. I can't work it out from coveralls.

**Comment by michaelhelmick** [comment]
@philgyford looks like api.py increased by 4 lines.

Yours: https://coveralls.io/builds/13616507/source?filename=twython%2Fapi.py
Master: https://coveralls.io/builds/13633835/source?filename=twython%2Fapi.py

You can see lines that are hit and aren't. It shouldn't be too big of a change though. Looks like nothing actually is missed.

**Comment by michaelhelmick** [comment]
It looks like Python 2.x fails on Travis https://travis-ci.org/ryanmcgrath/twython/builds/284748942?utm_source=github_status&utm_medium=notification

**Comment by philgyford** [comment]
Whoops, I'll fix it later today/tomorrow. Getting so used to python 3 these days I forget about 2!

**Comment by philgyford** [comment]
I've:

* Fixed the python 2 issue
* Added another couple of `html_for_tweet()` tests to help bump the coverage back up a bit
* Got rid of some un-needed data from some of the test tweet objects

**Comment by philgyford** [comment]
BTW, I was thinking it would make things a bit easier to follow if the test tweets were nicely-formatted JSON, that was loaded in to use in tests, rather than already being compact python dicts. I was just wary of messing around with things too much. Sound a good idea?

**Comment by michaelhelmick** [comment]
@philgyford I think a python file with dicts (that are formatted nicely) or a JSON file would be nice. Either or would achieve the "_same_" knowledge to edit. `config.py` looks like it just has a bunch of one line dicts :(

**Comment by philgyford** [comment]
Whoops... do you have any idea how I'd reference a file like `tests/tweets/basic.json` from within a test, in a way that Travis etc will find it? That's worked for me before, but not this time!

**Comment by philgyford** [comment]
Phew, got it :) I think that's me done for now.

**Pull request merged**
