### PR TITLE
Cursor fix

### PR DESCRIPTION
**Pull request by eoso**
I fixed the cursor function to grab next pages of results when using the search function or one of the timeline functions. (Copy of previous pull request in which I had made a mistake with git branches.)

### CODE REVIEW

**Comment by michaelhelmick** [comment]
Was there an issue out for this PR?

**Comment by michaelhelmick** [comment]
Hi @eoso. Just re-uping

https://github.com/ryanmcgrath/twython/pull/386#issuecomment-130727647

**Comment by eoso** [comment]
Hey, thanks for getting my attention. I got busy. 

I noticed that when iterator mode uses since_ids, the cursor generator would start repeatedly yielding the same tweet once it reached the end of it's initial block of tweets. 

A few people had similar problems:  #365,  #325.

I noticed that someone had written a fix (which also included a sleep function) over a year ago but wasn't pulled:  #332

I can post some code later as well, if that's helpful, but don't have the time to get it setup at the moment.

**Comment by ababino** [comment]
Dear all, 
I had a problem with cursor and get_user_timeline but the fix by @eoso solve it! Please, if it is possible,  mearge the fix. If there is anything I can help with please let me know.
Bests

**Comment by AmauryCarrade** [comment]
Same here, this PR fixed the cursors bug with `get_user_timeline` for me.

**Comment by dannguyen** [comment]
I was writing a tutorial on how to use Twython for collecting tweets, particularly,  paginating through a user's available timeline and was wondering if there was an estimated ETA for merging in this pull request into a new release?

**Comment by michaelhelmick** [comment]
Re-pinging @eoso?

**Comment by decklord** [comment]
Can you merge this?

**Comment by michaelhelmick** [comment]
By popular demand, I will merge this despite tests. I'll try and do a release soon.

**Comment by michaelhelmick** [comment]
Twython 3.7.0 is now available on PyPI

**Pull request merged**
